In [166]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [167]:
dataset=pd.read_csv('heart.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [168]:
dataset.info


<bound method DataFrame.info of       age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]>

In [169]:
X

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [170]:
y

array([0, 0, 0, ..., 0, 1, 0])

In [171]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [172]:
X_train

array([[67.,  1.,  0., ...,  1.,  3.,  2.],
       [50.,  1.,  0., ...,  1.,  0.,  3.],
       [65.,  1.,  3., ...,  1.,  1.,  2.],
       ...,
       [65.,  1.,  3., ...,  1.,  1.,  2.],
       [67.,  1.,  0., ...,  1.,  0.,  2.],
       [60.,  1.,  2., ...,  1.,  0.,  2.]])

In [173]:
X_test

array([[44.,  1.,  2., ...,  2.,  0.,  2.],
       [58.,  0.,  1., ...,  2.,  2.,  2.],
       [63.,  1.,  0., ...,  2.,  2.,  3.],
       ...,
       [69.,  1.,  3., ...,  1.,  1.,  2.],
       [62.,  1.,  2., ...,  1.,  3.,  3.],
       [64.,  1.,  3., ...,  1.,  0.,  2.]])

In [174]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,

In [175]:
y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [176]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [177]:
X_train

array([[ 1.3756016 ,  0.64371161, -0.92094523, ..., -0.66196846,
         2.16167937, -0.52198613],
       [-0.50461767,  0.64371161, -0.92094523, ..., -0.66196846,
        -0.73565005,  1.09448705],
       [ 1.15439933,  0.64371161,  1.98570929, ..., -0.66196846,
         0.23012642, -0.52198613],
       ...,
       [ 1.15439933,  0.64371161,  1.98570929, ..., -0.66196846,
         0.23012642, -0.52198613],
       [ 1.3756016 ,  0.64371161, -0.92094523, ..., -0.66196846,
        -0.73565005, -0.52198613],
       [ 0.60139366,  0.64371161,  1.01682445, ..., -0.66196846,
        -0.73565005, -0.52198613]])

In [178]:
X_test

array([[-1.16822447,  0.64371161,  1.01682445, ...,  0.96749237,
        -0.73565005, -0.52198613],
       [ 0.3801914 , -1.55349069,  0.04793961, ...,  0.96749237,
         1.1959029 , -0.52198613],
       [ 0.93319706,  0.64371161, -0.92094523, ...,  0.96749237,
         1.1959029 ,  1.09448705],
       ...,
       [ 1.59680387,  0.64371161,  1.98570929, ..., -0.66196846,
         0.23012642, -0.52198613],
       [ 0.82259593,  0.64371161,  1.01682445, ..., -0.66196846,
         2.16167937,  1.09448705],
       [ 1.0437982 ,  0.64371161,  1.98570929, ..., -0.66196846,
        -0.73565005, -0.52198613]])

In [179]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [185]:
if classifier.predict([[52	,1,	0	,125,	212,	0	,1	,168,	0	,1,	2,	2,	3]]) ==0:
    print("No")
else:
    print("Yes")

No


In [181]:
y_pred=classifier.predict(X_test)

In [182]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [183]:
cm

array([[ 99,  24],
       [ 12, 122]])

In [184]:
ac

0.8599221789883269