In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataset=pd.read_csv('insurance.csv')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
# Import necessary classes for encoding and transformation
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Define the ColumnTransformer with multiple columns for OneHotEncoder
# Assume columns 1, 3, and 5 are the categorical columns
ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(), [1, 4, 5])
], remainder='passthrough')

# Apply the ColumnTransformer to the feature set
X = np.array(ct.fit_transform(X))

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 19, 27.9, 0],
       [0.0, 1.0, 1.0, ..., 18, 33.77, 1],
       [0.0, 1.0, 1.0, ..., 28, 33.0, 3],
       ...,
       [1.0, 0.0, 1.0, ..., 18, 36.85, 0],
       [1.0, 0.0, 1.0, ..., 21, 25.8, 0],
       [1.0, 0.0, 0.0, ..., 61, 29.07, 0]], dtype=object)

In [ ]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train

array([[0.0, 1.0, 0.0, ..., 37, 34.1, 4],
       [0.0, 1.0, 1.0, ..., 18, 34.43, 0],
       [1.0, 0.0, 0.0, ..., 23, 36.67, 2],
       ...,
       [0.0, 1.0, 1.0, ..., 40, 25.08, 0],
       [0.0, 1.0, 1.0, ..., 19, 35.53, 0],
       [1.0, 0.0, 1.0, ..., 33, 18.5, 1]], dtype=object)

In [ ]:
y_train

array([40182.246 ,  1137.4697, 38511.6283, ...,  5415.6612,  1646.4297,
        4766.022 ])

In [ ]:
X_test

array([[0.0, 1.0, 1.0, ..., 52, 30.2, 1],
       [1.0, 0.0, 1.0, ..., 47, 29.37, 1],
       [0.0, 1.0, 0.0, ..., 48, 40.565, 2],
       ...,
       [0.0, 1.0, 1.0, ..., 57, 40.28, 0],
       [1.0, 0.0, 0.0, ..., 30, 39.05, 3],
       [0.0, 1.0, 1.0, ..., 46, 24.795, 3]], dtype=object)

In [ ]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=40,random_state=0)
regressor.fit(X_train,y_train)


RandomForestRegressor(n_estimators=40, random_state=0)

In [ ]:

# Function to encode a new sample and make predictions
def predict_new_sample(sample, ct, regressor):
    # Transform the new sample using the ColumnTransformer
    sample_encoded = np.array(ct.transform([sample]))

    # Make a prediction using the trained regressor
    prediction = regressor.predict(sample_encoded)

    return prediction

# New sample to predict (make sure this matches the format used in the dataset)
new_sample = [19, 'female', 27.9, 0, 'yes', 'southwest']

# Make a prediction for the new sample
prediction = predict_new_sample(new_sample, ct, regressor)
print("Prediction for the new sample:", prediction)

Prediction for the new sample: [16971.68514]


In [ ]:
y_pred=regressor.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8749339033676494